### ISSUE TITLE
Where is the source code for version 0.3?

### ISSUE THREAD

**Issue by elpiel** [timothee-haudebourg/langtag#1]
Hello,
I was checking your library for parsing Accept-language header but I've noticed that the source code in this repository is from 2 years ago and is only for `0.2`.
Where can I find the 0.3 source-code?

There also seems to be no tags associated with the releases.

**Comment by timothee-haudebourg** [comment]
Seems like I messed up somewhere indeed.

**Comment by timothee-haudebourg** [comment]
Everything should be up to date on this repo now.
